# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 12:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fund', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('mail_code', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('name_leader', models.CharField(max_length=100)),
                ('surname_leader', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=b'')),
                ('age_of_fund', models.CharField(max_length=100)),
                ('img_leader', models.ImageField(upload_to=b'')),
                ('link_facebook', models.CharField(max_length=100)),
                ('link_linkedIn', models.CharField(max_length=100)),
                ('add_info_fond', models.CharField(max_length=2000)),
                ('add_info_boss', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'fund',
            },
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('born_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('mail_code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format:', regex='\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=b'')),
                ('link_facebook', models.CharField(max_length=100)),
                ('link_linkedIn', models.CharField(max_length=100)),
                ('invest_time', models.CharField(max_length=100)),
                ('investments', models.BooleanField(default=False)),
                ('add_info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'trader',
            },
        ),
    ]
