# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='add_info_fond',
            new_name='add_info_fund',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='add_info_boss',
            new_name='add_info_leader',
        ),
    ]
