# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20171108_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='born_date',
            new_name='birthday',
        ),
    ]
