# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20171109_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='add_info',
            field=models.CharField(max_length=2000),
        ),
    ]
