# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171109_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='investments',
            field=models.CharField(max_length=10),
        ),
    ]
