# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171109_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'investor',
            },
        ),
        migrations.AlterField(
            model_name='fund',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='trader',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
