# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20171113_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='logo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
