# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171113_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='img'),
        ),
    ]
