# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20171113_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='link_facebook',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='trader',
            name='link_linkedIn',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
