# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20171113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='img_leader',
            field=models.ImageField(blank=True, default=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='img'),
        ),
    ]
