# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20171114_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='password',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='password',
        ),
    ]
